version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4600:4600"
    volumes:
      - .:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --port 4600